---
title: "Write Up Linear Model with Prediction"
author: "Leonel D. Bautista"
date: "10/19/23"
output:
  html_document: default 
  pdf_document: default
---

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE,echo=FALSE}
require(tidyverse)
require(tigerstats)
require(knitr)
require(foreign)
install.packages("car")
require(car)

mydata <- read.csv(file="https://onlinestatbook.com/case_studies_rvls/physical_strength/data.txt",sep="",header=TRUE)

```

# Introduction

($H_0$): There is no meaningful difference in how well arm strength, grip strength, or a combination of both can predict SIMS scores.

($H_A$): There is a noticeable difference in how well arm strength, grip strength, or a combination of both can predict SIMS scores. 

```{r}
model1 <- lm(SIMS~ARM,data=mydata)
plot(SIMS~ARM,data=mydata)
abline(model1)
specificdata1 <- data.frame(GRIP = 94, ARM = 88)
predict(model1, specificdata1, interval="prediction")
cor(mydata$SIMS, mydata$ARM)
```

  

